apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3
          env:
            - name: SERVICES
              value: "s3,sqs"
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.env.AWS_DEFAULT_REGION }}"
          ports:
            - containerPort: 4566
          readinessProbe:
            httpGet: { path: /_localstack/health, port: 4566 }
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
    - name: edge
      port: 4566
      targetPort: 4566
  type: ClusterIP
