apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:2.2.0
          env:
            - name: SERVICES
              value: "s3,sqs"
            - name: DEBUG
              value: "1"
            - name: DEFAULT_REGION
              value: "us-west-2"
            - name: DATA_DIR
              value: "/tmp/localstack/data"
          ports:
            - containerPort: 4566
          livenessProbe:
            httpGet:
              path: /
              port: 4566
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
    - port: 4566
      targetPort: 4566