apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.worker }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_DEFAULT_REGION
              valueFrom: { configMapKeyRef: { name: image-resizer-config, key: AWS_DEFAULT_REGION } }
            - name: INPUT_BUCKET
              valueFrom: { configMapKeyRef: { name: image-resizer-config, key: INPUT_BUCKET } }
            - name: OUTPUT_BUCKET
              valueFrom: { configMapKeyRef: { name: image-resizer-config, key: OUTPUT_BUCKET } }
            - name: AWS_ENDPOINT
              valueFrom: { configMapKeyRef: { name: image-resizer-config, key: AWS_ENDPOINT } }
            - name: QUEUE_URL
              valueFrom: { configMapKeyRef: { name: image-resizer-config, key: QUEUE_URL } }
