---
name: cd-local

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build_and_deploy_local:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        run: |
          set -euxo pipefail
          echo "${{ github.token }}" \
            | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build API image and export name
        run: |
          set -euxo pipefail
          API_NAME="ghcr.io/${{ github.repository_owner }}/image-resizer-api"
          API_IMG="${API_NAME}:${{ github.sha }}"
          docker build -t "$API_IMG" api
          echo "API_IMG=$API_IMG" >> $GITHUB_ENV

      - name: Build Worker image and export name
        run: |
          set -euxo pipefail
          WORKER_NAME="ghcr.io/${{ github.repository_owner }}/image-resizer-worker"
          WORKER_IMG="${WORKER_NAME}:${{ github.sha }}"
          docker build -t "$WORKER_IMG" worker
          echo "WORKER_IMG=$WORKER_IMG" >> $GITHUB_ENV

      - name: Debug: show exported image variables
        run: |
          set -euxo pipefail
          echo "DEBUG: API_IMG='$API_IMG'"
          echo "DEBUG: WORKER_IMG='$WORKER_IMG'"

      - name: Push images to GHCR (optional)
        run: |
          set -euxo pipefail
          docker push "$API_IMG"
          docker push "$WORKER_IMG"

      - name: Create kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: kind

      - name: Load images into kind
        run: |
          set -euxo pipefail
          kind load docker-image "$API_IMG" --name kind
          kind load docker-image "$WORKER_IMG" --name kind

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy LocalStack to kind
        run: |
          set -euxo pipefail
          kubectl apply -f deploy/localstack-deploy.yaml
          kubectl wait --for=condition=ready pod -l app=localstack --timeout=180s

      - name: Helm upgrade/install image-resizer (local values)
        run: |
          set -euxo pipefail
          helm upgrade --install image-resizer deploy/charts/image-resizer -f deploy/charts/image-resizer/values-local.yaml --wait --timeout 5m

      - name: Smoke test API (port-forward + upload)
        run: |
          set -euxo pipefail
          kubectl port-forward svc/api 8080:8080 >/tmp/portforward.log 2
