---
name: cd-local

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build_and_deploy_local:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        run: |
          set -euxo pipefail
          echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build API image and export name
        run: |
          set -euxo pipefail
          API_NAME="ghcr.io/${{ github.repository_owner }}/image-resizer-api"
          API_IMG="${API_NAME}:${{ github.sha }}"
          docker build -t "$API_IMG" api
          echo "API_IMG=$API_IMG" >> $GITHUB_ENV

      - name: Build Worker image and export name
        run: |
          set -euxo pipefail
          WORKER_NAME="ghcr.io/${{ github.repository_owner }}/image-resizer-worker"
          WORKER_IMG="${WORKER_NAME}:${{ github.sha }}"
          docker build -t "$WORKER_IMG" worker
          echo "WORKER_IMG=$WORKER_IMG" >> $GITHUB_ENV

      - name: Debug: show exported image variables
        run: |
          set -euxo pipefail
          # Use parameter expansion with default to avoid unbound-variable in debug
          printf "API_IMG=%s\n" "${API_IMG:-<not set>}"
          printf "WORKER_IMG=%s\n" "${WORKER_IMG:-<not set>}"

      - name: Push images to GHCR (optional for remote pull)
        run: |
          set -euxo pipefail
          # Safely test for variables instead of letting 'set -u' abort with unhelpful message.

