---
name: cd-local

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build_push_validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Example step
        run: echo "workflow triggers OK"